### ISSUE TITLE
Simplify kelon configuration

### ISSUE THREAD

**Issue by dcseifert** [Foundato/kelon#157]
The internal configuration process of kelon should be as simple as possible. Therefore following changes have to be made:

- [ ] Remove opa.yml (should be automatically created by kelon)
- [ ] Set Call-Operands default files for all supported datastore (could be overwritten)
- [ ] Merge api.yml and datastore.yml into one config

Following configuration might be used as an example:

```yaml
configs:
  labels:
    app: Kelon
    region: europe-west3
    environment: development

datastores:
  mysql:
    type: mysql
    connection:
      host: "localhost"
      port: 5432
      database: mysql
      user: mysql
      password: SuperSecure
    metadata:
      default_schema: default
    entity_schemas:
      mysql:
        appstore:
          entities:
            - name: users
            - name: user_followers
              alias: followers

apis:
  - path-prefix: /api
    datastore: mysql
    mappings:
      - path: /.*
        package: default
      # Create article
      - path: /articles
        package: articles
        methods:
          - POST
      # Get articles by author
      - path: /articles
        package: articles
        methods:
          - GET
        queries:
          - author
```

Following program arguments were also discussed:
* --policy-dir (optional)
* --policy-hot-reload (default: true)
* --config
* --dry-run (default: false)
* --default-decision (default: DENY)
