### ISSUE TITLE
Make property mappings for Istio-Adapter configurable

### ISSUE THREAD

**Issue by dcseifert** [Foundato/kelon#67]
# Description

Right now Kelon's Istio-Adapter has the possibility to map configured action-properties from the authorization-template already implemented but the configuration of this mapping is hardcoded.

i.e. 

[file: sample_operator_cfg.yaml] configuration with one property "authorization"
```yaml
# instance for template authorization
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: authinfo
  namespace: istio-system
spec:
  template: authorization
  params:
    subject:
      user: source.uid | ""
    action:
      namespace: destination.namespace | "default"
      service: destination.service.host | ""
      path: request.path | "/api/mysql/apps/1"
      method: request.method | "GET"
      properties:
        authorization: request.headers["authorization"] | ""
```

[file: kelon-istio-adapter.go] mapping for property authorization
```golang
// Mapped type of a configured kelon-istio property
type PropertyType string

const (
	// Set configured property as request header
	PropHeader PropertyType = "header"
)

// Mappings for properties (They should be loaded from external config later on)
var propertyTypeMappings map[string]PropertyType = map[string]PropertyType{
	"authorization": PropHeader,
}
```
# Outcome

The configuration of this mapping can be configured from outside via i.e. a yaml-config
